language: php
php:
  - "5.6"
  - "7.0"
  - "7.1"
  - "7.2"
  - "7.3"
  - "7.4"
  - nightly

matrix:
  include:
    - php: "5.4"
      dist: trusty
    - php: "5.5"
      dist: trusty
    - php: hhvm-3.30
      dist: trusty
  allow_failures:
    - php: nightly

sudo: false
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --dev
  - mkdir -p build/logs

after_script:
  - php vendor/bin/coveralls
